### ISSUE TITLE
New update for mediapipe hand tracking

### ISSUE THREAD

**Issue by Saltb0xApps** [noppefoxwolf/HandTracker#1]
Hi! Love the work you've done here in generating the mediapipe hand tracking iOS framework.

Mediapipe has launched a new update - https://github.com/google/mediapipe/releases/tag/v0.7.5

Would it be possible for you to update the SDK for this new version?
The results in improvements are huge as seen here: https://twitter.com/GoogleAI/status/1265319835283537921

**Comment by Saltb0xApps** [comment]
@noppefoxwolf also, if you'd be interested in working on an hourly/contract based remote work, let me know! i have a couple of commercial projects related to Machine Learning+iOS. 

_Sorry for adding this as a comment to a github issue, i don't really have any other way of messaging you_

**Comment by noppefoxwolf** [comment]
@Saltb0xApps Hi, Thank you for your comment.
I released HandTracker 1.3.
This release build with latest mediapipe, version 0.7.5.
https://github.com/noppefoxwolf/HandTracker/releases/tag/1.3

Enjoy your hacking! (Give me a ⭐️ミ)

**Comment by Saltb0xApps** [comment]
@noppefoxwolf thanks! appreciate the effort. Would it be possible for you to note the steps on how to apply this to other mediapipe frameworks? 

Also, you might want to check out the new dense face landmarking by mediapipe, which is very cool! https://github.com/google/mediapipe/blob/master/mediapipe/docs/face_mesh_mobile_gpu.md

**Comment by noppefoxwolf** [comment]
@Saltb0xApps If you want customize pipeline, you should write BUILD file and build yourself.
You can read a BUILD file of HandTracker [here](https://github.com/noppefoxwolf/HandTracker/blob/master/Sources/BUILD). Customize and try it!

**Comment by Saltb0xApps** [comment]
@noppefoxwolf perfect, that's exactly what i was looking for! Thanks, i'll check it out. :)
